name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  # TODO: Get this to not auto-disable itself every 60 days (https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule)
  schedule:
    - cron: "46 4 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  vencord:
    name: Build Vencord
    runs-on: ubuntu-latest
    steps:
      - name: Get latest commit
        run: |
          COMMITS=$(curl -fsSL https://api.github.com/repos/Vencord/builds/commits)
          echo "VENCORD_BUILDS_COMMIT=$(echo $COMMITS | jq -r '.[0].sha')" >> $GITHUB_ENV
          echo "VENCORD_COMMIT=$(echo $COMMITS | jq -r '.[0].commit.message | match("https://github\\.com/Vendicated/Vencord/commit/(\\w+)").captures[0].string')" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          repository: 'Vendicated/Vencord'
          ref: '${{ env.VENCORD_COMMIT }}'
          path: 'in/vencord'

      - name: Create Vencord plugin artifacts
        run: |
          mkdir -p out/vencord/plugins

          for entry in in/vencord/src/plugins/*; do
            dirName=$(basename $entry)

            if [ -d "$entry" ] && [[ $dirName != _* ]]; then
              tar -czf out/vencord/plugins/$dirName.tar.gz -C $entry .
            fi
          done

      - name: Create vencord.json
        run: |
          echo $VENCORD_BUILDS_COMMIT
          curl -fsSL "https://raw.githubusercontent.com/Vencord/builds/$VENCORD_BUILDS_COMMIT/plugins.json" > out/vencord/plugins.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vencord
          path: out/

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: [vencord]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - run: |
          tree $GITHUB_WORKSPACE

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
